mysql:
  host: localhost
  password: root
  port: 3306
  user: root

ubuntu:
  domains_and_document_roots:
    domain-1.com: /home/ubuntu/domain-1.com
    sub-domain.domain-1.com: /home/ubuntu/sub-domain.domain-1.com
    domain-2.com: /home/ubuntu/domain-2.com
    sub-domain.domain-2.com: /home/ubuntu/sub-domain.domain-2.com
    domain-3.com: /home/ubuntu/domain-3.com
    sub-domain.domain-3.com: /home/ubuntu/sub-domain.domain-3.com
